[project]
name = "ytserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.10.4",
    "mcp>=1.10.1",
    "mcp[cli]>=1.9.4",
    "openai>=1.93.3",
    "youtube-transcript-api>=1.1.1",
]
